# Get server public ip
SERVER_IP="INSERT_SERVER_IP_HERE"
MAIL_IP="INSERT_MAIL_IP_HERE"


VNC_IPS="INSERT_VNC_IPS_HERE"
RDP_IPS="INSERT_RDP_IPS_HERE"

ExtReLabIP="INSERT_IP_APPLICATION_SERVER1_HERE,INSERT_IP_APPLICATION_SERVER2_HERE"
ExtReLabPort="8080:8083"
